[tool.ruff]
line-length = 127
exclude = [".git", "__pycache__", ".venv", "venv", "env", "test_output", "outputs", "artifacts/*/runs/*"]
# Enable a sensible default subset; projects can extend these later
select = ["E", "F", "W", "C", "B", "I"]

[tool.black]
line-length = 127
target-version = ["py310"]
include = '\.pyi?$'
exclude = '''
/(\
  \.git
| \.venv
| venv
| build
| dist
| test_output
| outputs
| artifacts
)/*'''

[tool.isort]
profile = "black"

[tool.ruff.per-file-ignores]
# allow test modules to use assert and have looser rules
"tests/**" = ["D", "S101"]
